354546

diff --git a/.github/workflows/stackhawk.yml b/.github/workflows/stackhawk.yml
--- a/.github/workflows/stackhawk.yml
+++ b/.github/workflows/stackhawk.yml
@@ -24,21 +24,26 @@ jobs:
           docker build -t myapp .  # Соберите ваш образ
           docker run --rm --detach --name myapp_container myapp  # Запустите контейнер вашего приложения
 
-      - name: Run Nginx with custom config
-        run: |
-          echo "server {
-            listen 80;
-            location / {
-                proxy_pass http://myapp_container:8080;  # Проксируем на ваш сервис
-                proxy_set_header Host \$host;
-                proxy_set_header X-Real-IP \$remote_addr;
-                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
-                proxy_set_header X-Forwarded-Proto \$scheme;
-            }
-          }" > nginx.conf
-
-          docker run --rm --detach --name nginx_test -p 8080:80 -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf nginx
-
+          - name: Create Nginx config file
+          run: |
+            echo "server {
+                listen 80;
+                location / {
+                    proxy_pass http://myapp_container:8080;  # Проксируем на ваш сервис
+                    proxy_set_header Host \$host;
+                    proxy_set_header X-Real-IP \$remote_addr;
+                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
+                    proxy_set_header X-Forwarded-Proto \$scheme;
+                }
+            }" > nginx.conf
+  
+        - name: Run Nginx with custom config
+          run: |
+            docker run --rm --detach --name nginx_test -p 8080:80 -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf nginx || (echo "Nginx failed to start" && exit 1)
+  
+        - name: Check Nginx logs for errors
+          run: |
+            docker logs nginx_test || echo "No logs available"
           
       - name: Check running containers
         run: docker ps
